/* registry — the one place the bench learns what components exist (Rule 9: one module, one job).
   Entry: id = component dir + file basename; hasJs = <id>.js exports init(root);
   deps = other component ids whose CSS must load first (e.g. top-bar embeds goo toggles). */
export const REGISTRY = [
  {
    id: 'portal-window',
    title: 'Portal window (zutomayo ratios)',
    note: 'RATIOS + two devices from zutomayo, NOT their look - read the CSS header before trusting the citation. Bar type at their 43%-of-bar-height, filled bar, double border, zero-blur 3px 3px 0. Colours are ours; theirs are pale pink + purple + drawn PNGs.',
    hasJs: false,
  },
  {
    id: 'palette',
    title: 'PALETTE (color tokens, live)',
    note: 'edit any token; overrides persist + recolor every component AND aggregate.html',
    hasJs: true,
  },
  {
    id: 'top-bar',
    title: 'Top bar (favicon+name / nav / toggles)',
    note: 'favicon+name left (SQUARE favicon), nav centered (lit pill), SMALL SQUARE SLAP toggles right (goo->slap swap 2026-08-11)',
    hasJs: true,
    deps: ['slap-toggle', 'favicon'],
  },
  {
    id: 'favicon',
    title: 'Favicon (clamped magnet + spin)',
    note: 'favicon.svg; magnetic but clamped to its box, spins on hover, links home; + SQUARE variant (2026-08-11)',
    hasJs: true,
  },
  {
    id: 'hero',
    title: 'Hero (harumaki + scene switch)',
    note: 'harumaki logo/tagline; background GOO switch Lanterns<->Bloom (slap->goo swap 2026-08-11; scene wiring is page-level)',
    hasJs: true,
    deps: ['goo-toggle'],
  },
  {
    id: 'goo-toggle',
    title: 'Gooey toggle (harumaki)',
    note: 'nicolasjesenberger xxmbvxL, recolored; magnetic',
    hasJs: true,
  },
  {
    id: 'slap-toggle',
    title: 'Slap toggle (hana / YarivFrd)',
    note: 'codepen.io/YarivFrd/pen/PEOJLj; dynamic flap label; magnetic; + SQUARE variant (2026-08-11)',
    hasJs: true,
  },
  {
    id: 'draw-in-icons',
    title: 'Tool icons (stephan draw-in)',
    note: 'stephanewillems draw-in; magnetic via base (icon = inner parallax); official SVGs owed. Cursor recolour circle REMOVED 2026-08-13 (Rod) - the clone desynced from the draw-in and the hover-reveal move belongs to the cards',
    hasJs: true,
  },
  {
    id: 'magnetic',
    title: 'Magnetic behavior (cursor-stick)',
    note: 'tdesero/dennissnellenberg API x chriskalafatis lerp - sources/magnetic-buttons.md',
    hasJs: true,
  },
  {
    id: 'drift-magnet',
    title: 'Drift + magnet BASE (drift x cursor-stick)',
    note: '2-axis drift (breakdance4fun) x magnet (dennissnellenberg) x graceful motion-off; supersedes magnetic',
    hasJs: true,
  },
  {
    id: 'cursor-glow',
    title: 'Cursor glow (cursor-as-lantern vignette)',
    note: 'brittanychiang/merodev full-page .cursorglow radial, recolored purple->gold; driven via cursor-coords',
    hasJs: true,
  },
  {
    id: 'button-kit',
    title: 'Button kit (stephan x hana x magnetic)',
    note: 'buttons strength 55, tags ripple + slight magnetic 25',
    hasJs: true,
  },
  {
    id: 'merged-card',
    title: 'Project cards (flip look x merged function)',
    note: 'flip-tile cover bento [6r2][6][6][12]; z-depth vars; glass toggle; dwell-flip',
    hasJs: true,
  },
  {
    id: 'card-tests',
    title: 'Card tests (A: magnet+drift / B: band-reveal)',
    note: 'behaviors on the REAL merged-card at scale + activation culling + live FPS; A=drift-magnet, B=yannesidibe glow',
    hasJs: true,
    deps: ['merged-card'],
  },
  {
    id: 'project-cards-expensive',
    title: 'Project cards (expensive)',
    note: 'COMBINED keeper: drift + magnet + glass band-reveal + back glow + parallax tilt; video on hover; now SQUARE tiles + pink STAR pin (Corners button flips back)',
    hasJs: true,
    deps: ['merged-card'],
  },
  {
    id: 'reel-band',
    title: 'Reel band (harumaki)',
    note: 'full-bleed at page level; sits ABOVE the cards',
    hasJs: false,
  },
  {
    id: 'glow-edge-tests',
    title: 'Glow edge tests (why the reveal reads as metal)',
    note: 'Rod 2026-08-13: the cursor band-reveal reads as a metal band. 7 isolated treatments + 1 stacked, on the REAL card. Shape untouched.',
    hasJs: true,
    deps: ['merged-card', 'project-cards-expensive'],
  },
  {
    id: 'seam-band',
    title: 'Seam band (ndt tiled / harumaki sheet)',
    note: 'painted transition between sections; ndt .borderpink 160px repeat-x @70% + main top_hr_cloud sheet 96px; ARTWORK OWED (--seam-art)',
    hasJs: false,
  },
  {
    id: 'edge-rails',
    title: 'Edge rails (harumaki /10/ curtain)',
    note: 'fixed full-height illustration pinned to both edges, sized by height, pointer-events none, hidden <=450px; ARTWORK OWED (--rail-art)',
    hasJs: false,
  },
  {
    id: 'dated-timeline',
    title: 'Dated timeline (harumaki /10/)',
    note: 'sticky date at top:100px beside each entry; 20% date / 4% tiled rule / 70% body; their #fef694 deliberately not copied',
    hasJs: false,
  },
  {
    id: 'picture-frame',
    title: 'Picture frame (109ichiki outer frame)',
    note: 'fixed inset 20px (15 mobile), rx 8 (6), 1px stroke; their SVG mask rebuilt as one outset box-shadow, no JS; --open = stroke only',
    hasJs: false,
  },
  {
    id: 'list-controls',
    title: 'List controls (stephan x hana x magnetic)',
    note: 'search w/ border-caret (atelierbram), ripple filters, hana empty content',
    hasJs: true,
  },
  {
    id: 'post-header',
    title: 'Post header (norikura decision)',
    note: 'sengoku-sourced centered title card',
    hasJs: false,
  },
  {
    id: 'tldr-callout',
    title: 'TL;DR callout (hana)',
    note: 'left-accent amber; deliberately distinct from the stamp takeaway',
    hasJs: false,
  },
  {
    id: 'quote-block',
    title: 'Quote (harumaki shape x hana type)',
    note: 'bare left bar + Shippori italic, per Rod’s remix spec',
    hasJs: false,
  },
  {
    id: 'code-block',
    title: 'Code block (hana terminal)',
    note: 'filename tab + copy, NO traffic lights',
    hasJs: true,
  },
  {
    id: 'stamp-callout',
    title: 'Stamp callout (takeaway)',
    note: 'Rod-provided stamp CSS — APPROVED',
    hasJs: false,
  },
  {
    id: 'site-footer',
    title: 'Footer (harumaki, about link)',
    note: 'nav links dropped per Rod; about-page self-link variant TBD',
    hasJs: false,
  },
  {
    id: 'washi-tape',
    title: 'Washi tape (site convention)',
    note: 'gneiss.place .taped (ex planity). ONE definition, three placements: top edge, left edge, L corners. Rod made it a site-wide marker 2026-08-21. Greybox hatch stands in for a real tape PNG.',
    hasJs: false,
  },
  {
    id: 'tag-badge',
    title: 'Tag badge (main site, squared)',
    note: "the LIVE .post-tag carried over and squared per the shape pass. Rod 2026-08-21: 'the squared tags from main FOR NOW' - a stand-in, not a designed element.",
    hasJs: false,
  },
  {
    id: 'section-head',
    title: 'Section head (harumaki ornament)',
    note: "Rod's pick 2026-08-22: centred label flanked by a ~, hairline under, no kicker. The ~ is a STAND-IN for harumakigohan.com's drawn squiggle (references/harumaki-heads/) - hand-drawn art replaces it later. Their ornament is pink; ours is gold, palette law.",
    hasJs: false,
  },
  {
    id: 'skills-row',
    title: 'Skills row (outline draw-in)',
    note: "Rod's pick 2026-08-22: simpleicons.org marks (CC0) stroked in deep gold, drawn in via pathLength=1 per stephanewillems. Unity/Unreal/Godot/Blender/Maya/Python/Git. C#, HLSL and Compute have NO official mark and are absent rather than faked.",
    hasJs: false,
  },
  {
    id: 'footer-line',
    title: 'Footer (one quiet line)',
    note: "Rod 2026-08-22: 'i really like the way we do our lab footers i think we should do them all like this'. ORIGIN ROD - the .labtag treatment promoted from tooling to a real element. A footnote, not a second nav. Supersedes the circular-citation site-footer, which should be retired at port.",
    hasJs: false,
  },
  {
    id: 'status-chip',
    title: 'Status chip + terminal (3 versions)',
    note: 'dimden bracket token / mikeklubnika registry ledger / terminal.shop editor lines. Dashed boxes are the MEASURED reservation: chip 100 x 20, terminal 675 x 172, read off about-blockout.html?v=panels at 1440. Per-version provenance in status-chip.css + status-chip.md.',
    hasJs: true,
  },
  {
    id: 'filter-pills',
    title: 'Filter pills (list-controls x button-kit)',
    note: 'REBUILT as a reuse, not a design: behaviour from list-controls (.is-active + the main site filter), box from button-kit .kit-tag. The earlier tab/bracket/underline set was rejected for re-inventing an interaction that was never open. Two law fixes stated on the page: .kit-tag squared to 6px, and --color-muted (banned blue) swapped to silver. Measures its own pill against WCAG 2.5.8 24px live.',
    hasJs: true,
    wide: true,
  },
  {
    id: 'view-all-button',
    title: 'View-all button (3 versions, measured)',
    note: 'A stripe.dev spec row / B MauriciAbad underline draw + Maxime Heckel arrow spacing / C button-kit reused with dennissnellenberg rising fill. Reservation 84.98 x 28 in a 1421 x 64 band; the page prints its own getBoundingClientRect fit. Requests M PLUS Rounded 300 itself because the site pages ask only for 400;500;700 and every weight-300 rule silently renders 400 without it.',
    hasJs: true,
    wide: true,
    deps: ['button-kit', 'section-head', '/redesign-lab/decisions.css'],
  },
  {
    id: 'code-block-real',
    title: 'Code block (chrome settled, 3 colour schemes)',
    note: 'D20 chrome (Maxime Heckel header strip, squared), re-confirmed by Rod 2026-08-23; the OPEN question is colour, so all three blocks are identical chrome and differ only in scheme: V1 Rod\'s own, V2 Inigo Quilez, V3 Catlike Coding dark. Sample is real HLSL from Rod\'s ComputeGrass post, picked because it exercises preprocessor / type / intrinsic / number / comment / SV_ semantics / swizzles.',
    hasJs: true,
    wide: true,
  },
  {
    id: 'post-header-real',
    title: 'Post header + metadata rail (3 separators)',
    note: 'The component had NO markup anywhere in the repo until this demo; every class here comes from post-header-real.css. SOURCE sources/stripe-dev-prose.md (CONFIRMED), sections aside-sidenote + heading. TIER Remixed, idea-origin theirs; ours is the squaring, the colours and the separator call. V1 dotted / V2 solid / V3 none + wider gaps. NO PICK IS RECORDED - it stays three versions until Rod picks.',
    hasJs: true,
    wide: true,
    deps: ['/redesign-lab/decisions.css'],
  },
  {
    id: 'prevnext-real',
    title: 'Prev / next (newer / older)',
    note: 'V4, two cards in two lanes, plus the three text versions it replaced kept beside it for the comparison. Reuses related-card-real for the card. Prints its measured lane against the blockout\'s reserved 345 x 44 - the overshoot is the card, not a bug.',
    hasJs: true,
    wide: true,
    deps: ['related-card-real', '/redesign-lab/decisions.css'],
  },
  {
    id: 'portrait-frame',
    title: 'Portrait frame (3 versions, 191 x 200)',
    note: 'The About rail portrait at its MEASURED reservation: 191 x 200 inside the 225px rail (about-blockout.html:40,41,170; analysis/2026-08-23-blockout-contract.md:39). The dashed gold ring IS that reservation, drawn as an outline so it costs no space. V1 no frame / V2 corner brackets / V3 named window. There is no portrait image in the repo, so the media slot says so in words rather than borrowing a face.',
    hasJs: false,
    deps: ['figure-real'],
  },
  {
    id: 'entry-row',
    title: 'Entry row (ramblings, 3 versions)',
    note: 'BENCH ONLY, nothing approved - see entry-row.md for tier, origin and open questions. A Eve verbatim (whole row is one link, tag is a WORD) / B the same row with filterable tags / C Eve\'s real row, date line + title only. The two dashed boxes are two DIFFERENT reservations that disagree: gold = this build\'s (title 838x30, blurb 1054x45), grey = the Eve hairline blockout\'s (752x28, 820x48). Readouts are live getBoundingClientRect.',
    hasJs: true,
    wide: true,
    deps: ['tag-badge'],
  },
  {
    id: 'empty-state',
    title: 'Empty state (3 versions, measured 930x60 / 1351x60)',
    note: 'Reservation read off the rendered blockouts at 1440: projects 930 x 60, ramblings 1351 x 60, height 60 on both. The dashed outline behind each version IS that reservation, drawn as an outline so it costs no layout space. V1 centred stack / V2 centred row / V3 split row, plus a section tracing where each sentence of the copy came from. Readouts are live getBoundingClientRect.',
    hasJs: true,
    deps: ['/redesign-lab/decisions.css'],
  },
  {
    id: 'page-title-desc',
    title: 'Page title + description (3 versions)',
    note: 'Links the REAL decisions.css rather than copying it, so the H1 ladder here cannot drift. .d-h1 is clamp(2.75rem, 7vw, 101px) - its size follows the VIEWPORT, so the readouts are only the blockout numbers at 1440. Reservations drawn behind each version: projects 930 x 44 / ramblings 380 x 100 centred / ramblings CHOSEN 220 x 26. No scene here; nothing in this component uses a fill, blur or shadow, so it behaves the same over the live ground.',
    hasJs: true,
    deps: ['/redesign-lab/decisions.css'],
  },
  {
    id: 'search-bar',
    title: 'Search bar (two carets, three reservations)',
    note: 'The box, the // sigil and the no-expand-animation rule are SETTLED (element-tracker.md:107 + decisions.css:426-435). The only open question is WHICH CARET, so both versions are the same box and differ in nothing else; each caret comes from a different verified external source. Reservations: projects 400 x 34, ramblings 1351 x 40 (as handed) and 360 x 40 (what the approved variant reserves). Fields carry Rod\'s real post and project titles.',
    hasJs: true,
  },
  {
    id: 'socials-row',
    title: 'Socials / Elsewhere (3 versions, 191 x 120)',
    note: 'The dashed box is the RESERVATION, not a drawn guide: 191 x 120 read off about-blockout.html at 1440 and recorded in analysis/2026-08-23-blockout-contract.md (ABOUT table, Socials). V1 Ring / V2 Names / V3 Marked. Every version is sized in px and em off a 0.75rem root, and the readout measures whatever actually rendered - if it disagrees with the .md or the .css, this is the one that ran.',
    hasJs: true,
  },
  {
    id: 'bio-block',
    title: 'Bio block (3 versions, About prose)',
    note: 'bio_intro + bio_more drawn INSIDE their measured reservation so the fit is visible rather than asserted: 675 x 112 and 675 x 138, gap 10, measured off about-blockout.html?v=panels at 1440 on 2026-08-23 (the labels on that page say 140 and 180; it renders 112 and 138). Copy is Rod\'s own, verbatim from tech-art/about.md front matter with his two em dashes turned into commas. V1 Panel / V2 Heading card / V3 Bare. Where the prose runs past the dashed box, that is real overflow.',
    hasJs: true,
    deps: ['/redesign-lab/decisions.css'],
  },
  {
    id: 'achievement-tile',
    title: 'Achievement tile + locked state (6 versions)',
    note: 'THE TILE AND THE LOCKED STATE ONLY, not the wall - Rod 2026-08-23: the trophy wall has no source and needs a design conversation first, so nothing here proposes an arrangement. Measured off about-blockout.html?v=panels at 1440: locked/empty 641 x 40, tile 88 x 31, wall flex-wrap gap 10 at 6 tiles per row inside 641. V1-V3 = how much chrome a locked slot gets (lit edge / value only / no slot); V4 hue swap = how locked reads; V5 silhouette = rarity; V6 the tile is the bar = metadata. Each version prints its own rendered size live.',
    hasJs: true,
  },
  {
    id: 'search-field',
    title: 'Search field (six sourced candidates)',
    note: 'Six candidates, each built from CSS read off the live site 2026-08-24; verbatim sources in sources/search-fields-2026-08-24.md. A ronja / B Paris Review desktop / C Paris Review mobile / D CINRA / E Craig Mod / F A24, each inside its two real reservations drawn as dashed outlines: 1134 x 50 (projects) and 340 x 47 (ramblings), measured at 1440. Of 102 gallery sites exactly two have an always-open inline search and both are browser defaults, so A is the only strict drop-in and it supplies no look at all. Rod picked A 2026-08-24. The filter behaviour lives in search-field.js and runs on final-projects / final-ramblings, not here - same as on the page this came from.',
    hasJs: false,
    deps: ['/redesign-lab/decisions.css'],
  },
  {
    id: 'callout-family',
    title: 'Callout family (3 versions of the box)',
    note: 'Three versions of the BOX only - the tape is already decided and is NOT re-judged here. Every category is drawn in every version so a RUN of callouts can be compared, which a single-callout card cannot show. V1 one shell, the variant changes one thing / V2 the quiet secondary rail / V3 the tape’s actual partner box. Copy is Rod’s own from _posts/tech-art/2026-03-20-ComputeGrass.md plus the two callouts the placement analysis found real homes for. The hana bloom behind it is the page’s own scene stand-in.',
    hasJs: true,
    deps: ['washi-tape'],
  },
  {
    id: 'skill-tile',
    title: 'Skill tile (3 boxes for one mark + flipper band)',
    note: 'NOT NEW: the marks, stroke, deep gold, pathLength=1, the 6s draw-in, the 0.09s stagger and the reduced-motion path - all of that is skills-row, approved 2026-08-22, linked and used untouched; the seven marks are byte-identical. NEW: the 150 x 150 BOX around a mark (V1 bare / V2 corner brackets that CLOSE on hover / V3 full frame retracting to brackets, the inverse) and the 1421 x 120 flipper band (F1 reuses slap-toggle, F2 is the source’s own arrangement). Rows 2 and 3 are cloned from row 1 by the script so each SVG path exists once.',
    hasJs: true,
    deps: ['skills-row', 'slap-toggle'],
  },
  {
    id: 'achievement-wall',
    title: 'Achievement wall (catalogue + detail)',
    note: 'Rod\'s interaction model 2026-08-24, verbatim: hovering shows the LAST hovered achievement\'s text on the right, clicking forces its border to shine and activates it. Two gestures, two jobs; LAST hovered is load-bearing, the panel never clears on mouseout. The 29 achievements are the live site\'s, transcribed from _javascript/modules/components/achievements.js (off limits to edit under D22); counts match the blockout: explorer 7, reader 6, interactor 8, secret 3, meta 5. Rim glow SOURCE sources/john-r-muir-glow-border.md (True, codepen ExzJjqL); giving it a real hover/focus trigger moves back TOWARD the source. Knobs and tuner are bench chrome and live in achievement-wall.bench.js.',
    hasJs: true,
    jsFile: 'achievement-wall.bench',
    wide: true,
    deps: ['/redesign-lab/decisions.css'],
  },
];
